project_name: lorawan-stack

changelog:
  skip: true

release:
  prerelease: auto

builds:
  - id: stack
    main: ./cmd/ttn-lw-stack
    binary: ttn-lw-stack
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

  - id: cli
    main: ./cmd/ttn-lw-cli
    binary: ttn-lw-cli
    ldflags:
    - -s
    - -w
    - -X go.thethings.network/lorawan-stack/pkg/version.BuildDate={{.Date}}
    - -X go.thethings.network/lorawan-stack/pkg/version.GitCommit={{.ShortCommit}}
    - -X go.thethings.network/lorawan-stack/pkg/version.TTN={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: stack
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - cli
      - stack
    files:
      - LICENSE
      - README.md
      - doc/**/*
      - docker-compose.yml
      - public/**/*
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

  - id: cli
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    builds:
      - cli
    files:
      - LICENSE
      - README.md
      - doc/**/*
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - ttn-lw-cli
      - ttn-lw-stack
    image_templates:
      - "rvolosatovs/lorawan-stack:latest"
      - "rvolosatovs/lorawan-stack:{{ .Major }}"
      - "rvolosatovs/lorawan-stack:{{ .Major }}.{{ .Minor }}"
      - "rvolosatovs/lorawan-stack:{{ .Version }}"
    skip_push: auto
    extra_files:
      - public
